// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Vdom = require("../src-ocaml/vdom.js");
var Block = require("bs-platform/lib/js/block.js");
var Tea_app = require("../src-ocaml/tea_app.js");
var Tea_html = require("../src-ocaml/tea_html.js");

function select(param_0) {
  return /* Select */[param_0];
}

function render_selected(param) {
  if (param) {
    return Tea_html.div(/* None */0, /* None */0, /* [] */0, /* :: */[
                /* Text */Block.__(1, ["you selected " + param[0]]),
                /* :: */[
                  Tea_html.div(/* None */0, /* None */0, /* :: */[
                        Vdom.onMsg("click", /* Delete */0),
                        /* [] */0
                      ], /* :: */[
                        /* Text */Block.__(1, ["delete selection"]),
                        /* [] */0
                      ]),
                  /* [] */0
                ]
              ]);
  } else {
    return Tea_html.div(/* None */0, /* None */0, /* [] */0, /* :: */[
                /* Text */Block.__(1, ["Nothing selected"]),
                /* [] */0
              ]);
  }
}

function lang(l, is_selected) {
  var msg = /* Select */[l];
  return Tea_html.li(/* None */0, /* None */0, /* :: */[
              Vdom.onMsg("click", msg),
              /* :: */[
                Vdom.style("color", "blue"),
                /* :: */[
                  is_selected ? Vdom.style("border", "1px solid black") : Tea_html.noProp,
                  /* :: */[
                    is_selected ? /* Attribute */Block.__(1, [
                          "",
                          "lang",
                          l
                        ]) : Tea_html.noProp,
                    /* [] */0
                  ]
                ]
              ]
            ], /* :: */[
              /* Text */Block.__(1, [l]),
              /* [] */0
            ]);
}

function render_languages(selected, languages) {
  var is_selected = function (selected, language) {
    if (selected) {
      return language === selected[0];
    } else {
      return false;
    }
  };
  var rendered = List.map((function (l) {
          return lang(l, is_selected(selected, l));
        }), languages);
  return Tea_html.ul(/* None */0, /* None */0, /* [] */0, rendered);
}

function update(state, param) {
  if (param) {
    return /* record */[
            /* selected : Some */[param[0]],
            /* languages */state[/* languages */1]
          ];
  } else {
    return /* record */[
            /* selected : None */0,
            /* languages */state[/* languages */1]
          ];
  }
}

function view(state) {
  return Tea_html.div(/* None */0, /* None */0, /* [] */0, /* :: */[
              render_selected(state[/* selected */0]),
              /* :: */[
                render_languages(state[/* selected */0], state[/* languages */1]),
                /* [] */0
              ]
            ]);
}

var partial_arg_000 = /* model : record */[
  /* selected : Some */["Erlang"],
  /* languages : :: */[
    "Erlang",
    /* :: */[
      "Ocaml",
      /* :: */[
        "Clojure",
        /* [] */0
      ]
    ]
  ]
];

var partial_arg = /* record */[
  partial_arg_000,
  /* update */update,
  /* view */view
];

function main(param, param$1) {
  return Tea_app.beginnerProgram(partial_arg, param, param$1);
}

var $$delete = /* Delete */0;

exports.select = select;
exports.$$delete = $$delete;
exports.render_selected = render_selected;
exports.lang = lang;
exports.render_languages = render_languages;
exports.update = update;
exports.view = view;
exports.main = main;
/* Tea_html Not a pure module */
