version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  # Below is the definition of your job to build and test your app, you can rename and customize it as you want.
  build-and-test:
    docker:
      - image: cimg/node:14.17.0

    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: npm install
      - run: npm run build

workflows:
  sample:
    jobs:
      - build-and-test
      # For running simple node tests, you could optionally use the node/test job from the orb to replicate and replace the job above in fewer lines.
      # - node/test
