// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var Result;

var Cmd;

var Sub;

var App;

var Debug;

var Html;

var Html2;

var Svg;

var Task;

var Program;

var Time;

var Json;

var Navigation;

var Random;

var AnimationFrame;

var Mouse;

var Http;

var Ex;

exports.Result = Result;
exports.Cmd = Cmd;
exports.Sub = Sub;
exports.App = App;
exports.Debug = Debug;
exports.Html = Html;
exports.Html2 = Html2;
exports.Svg = Svg;
exports.Task = Task;
exports.Program = Program;
exports.Time = Time;
exports.Json = Json;
exports.Navigation = Navigation;
exports.Random = Random;
exports.AnimationFrame = AnimationFrame;
exports.Mouse = Mouse;
exports.Http = Http;
exports.Ex = Ex;
/* No side effect */
