// Generated by BUCKLESCRIPT VERSION 1.7.5, PLEASE EDIT WITH CARE
'use strict';

var List     = require("bs-platform/lib/js/list.js");
var Vdom     = require("./vdom.js");
var Block    = require("bs-platform/lib/js/block.js");
var Curry    = require("bs-platform/lib/js/curry.js");
var $$String = require("bs-platform/lib/js/string.js");

function text(str) {
  return /* Text */Block.__(1, [str]);
}

var lazy1 = Vdom.lazyGen;

function node($staropt$star, tagName, $staropt$star$1, $staropt$star$2, props, nodes) {
  var namespace = $staropt$star ? $staropt$star[0] : "";
  var key = $staropt$star$1 ? $staropt$star$1[0] : "";
  var unique = $staropt$star$2 ? $staropt$star$2[0] : "";
  return Vdom.fullnode(namespace, tagName, key, unique, props, nodes);
}

function br(props) {
  return Vdom.fullnode("", "br", "br", "br", props, /* [] */0);
}

function br$prime($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star ? $staropt$star[0] : "";
  var unique = $staropt$star$1 ? $staropt$star$1[0] : "";
  return Vdom.fullnode("", "br", key, unique, props, nodes);
}

function div($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star ? $staropt$star[0] : "";
  var unique = $staropt$star$1 ? $staropt$star$1[0] : "";
  return Vdom.fullnode("", "div", key, unique, props, nodes);
}

function span($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star ? $staropt$star[0] : "";
  var unique = $staropt$star$1 ? $staropt$star$1[0] : "";
  return Vdom.fullnode("", "span", key, unique, props, nodes);
}

function p($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star ? $staropt$star[0] : "";
  var unique = $staropt$star$1 ? $staropt$star$1[0] : "";
  return Vdom.fullnode("", "p", key, unique, props, nodes);
}

function pre($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star ? $staropt$star[0] : "";
  var unique = $staropt$star$1 ? $staropt$star$1[0] : "";
  return Vdom.fullnode("", "pre", key, unique, props, nodes);
}

function a($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star ? $staropt$star[0] : "";
  var unique = $staropt$star$1 ? $staropt$star$1[0] : "";
  return Vdom.fullnode("", "a", key, unique, props, nodes);
}

function section($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star ? $staropt$star[0] : "";
  var unique = $staropt$star$1 ? $staropt$star$1[0] : "";
  return Vdom.fullnode("", "section", key, unique, props, nodes);
}

function header($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star ? $staropt$star[0] : "";
  var unique = $staropt$star$1 ? $staropt$star$1[0] : "";
  return Vdom.fullnode("", "header", key, unique, props, nodes);
}

function footer($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star ? $staropt$star[0] : "";
  var unique = $staropt$star$1 ? $staropt$star$1[0] : "";
  return Vdom.fullnode("", "footer", key, unique, props, nodes);
}

function h1($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star ? $staropt$star[0] : "";
  var unique = $staropt$star$1 ? $staropt$star$1[0] : "";
  return Vdom.fullnode("", "h1", key, unique, props, nodes);
}

function h2($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star ? $staropt$star[0] : "";
  var unique = $staropt$star$1 ? $staropt$star$1[0] : "";
  return Vdom.fullnode("", "h2", key, unique, props, nodes);
}

function h3($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star ? $staropt$star[0] : "";
  var unique = $staropt$star$1 ? $staropt$star$1[0] : "";
  return Vdom.fullnode("", "h3", key, unique, props, nodes);
}

function h4($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star ? $staropt$star[0] : "";
  var unique = $staropt$star$1 ? $staropt$star$1[0] : "";
  return Vdom.fullnode("", "h4", key, unique, props, nodes);
}

function h5($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star ? $staropt$star[0] : "";
  var unique = $staropt$star$1 ? $staropt$star$1[0] : "";
  return Vdom.fullnode("", "h5", key, unique, props, nodes);
}

function h6($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star ? $staropt$star[0] : "";
  var unique = $staropt$star$1 ? $staropt$star$1[0] : "";
  return Vdom.fullnode("", "h6", key, unique, props, nodes);
}

function i($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star ? $staropt$star[0] : "";
  var unique = $staropt$star$1 ? $staropt$star$1[0] : "";
  return Vdom.fullnode("", "i", key, unique, props, nodes);
}

function strong($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star ? $staropt$star[0] : "";
  var unique = $staropt$star$1 ? $staropt$star$1[0] : "";
  return Vdom.fullnode("", "strong", key, unique, props, nodes);
}

function button($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star ? $staropt$star[0] : "";
  var unique = $staropt$star$1 ? $staropt$star$1[0] : "";
  return Vdom.fullnode("", "button", key, unique, props, nodes);
}

function input$prime($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star ? $staropt$star[0] : "";
  var unique = $staropt$star$1 ? $staropt$star$1[0] : "";
  return Vdom.fullnode("", "input", key, unique, props, nodes);
}

function textarea($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star ? $staropt$star[0] : "";
  var unique = $staropt$star$1 ? $staropt$star$1[0] : "";
  return Vdom.fullnode("", "textarea", key, unique, props, nodes);
}

function label($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star ? $staropt$star[0] : "";
  var unique = $staropt$star$1 ? $staropt$star$1[0] : "";
  return Vdom.fullnode("", "label", key, unique, props, nodes);
}

function ul($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star ? $staropt$star[0] : "";
  var unique = $staropt$star$1 ? $staropt$star$1[0] : "";
  return Vdom.fullnode("", "ul", key, unique, props, nodes);
}

function ol($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star ? $staropt$star[0] : "";
  var unique = $staropt$star$1 ? $staropt$star$1[0] : "";
  return Vdom.fullnode("", "ol", key, unique, props, nodes);
}

function li($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star ? $staropt$star[0] : "";
  var unique = $staropt$star$1 ? $staropt$star$1[0] : "";
  return Vdom.fullnode("", "li", key, unique, props, nodes);
}

function table($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star ? $staropt$star[0] : "";
  var unique = $staropt$star$1 ? $staropt$star$1[0] : "";
  return Vdom.fullnode("", "table", key, unique, props, nodes);
}

function thead($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star ? $staropt$star[0] : "";
  var unique = $staropt$star$1 ? $staropt$star$1[0] : "";
  return Vdom.fullnode("", "thead", key, unique, props, nodes);
}

function tfoot($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star ? $staropt$star[0] : "";
  var unique = $staropt$star$1 ? $staropt$star$1[0] : "";
  return Vdom.fullnode("", "tfoot", key, unique, props, nodes);
}

function tbody($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star ? $staropt$star[0] : "";
  var unique = $staropt$star$1 ? $staropt$star$1[0] : "";
  return Vdom.fullnode("", "tbody", key, unique, props, nodes);
}

function th($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star ? $staropt$star[0] : "";
  var unique = $staropt$star$1 ? $staropt$star$1[0] : "";
  return Vdom.fullnode("", "th", key, unique, props, nodes);
}

function tr($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star ? $staropt$star[0] : "";
  var unique = $staropt$star$1 ? $staropt$star$1[0] : "";
  return Vdom.fullnode("", "tr", key, unique, props, nodes);
}

function td($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star ? $staropt$star[0] : "";
  var unique = $staropt$star$1 ? $staropt$star$1[0] : "";
  return Vdom.fullnode("", "td", key, unique, props, nodes);
}

function progress($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star ? $staropt$star[0] : "";
  var unique = $staropt$star$1 ? $staropt$star$1[0] : "";
  return Vdom.fullnode("", "progress", key, unique, props, nodes);
}

function img($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star ? $staropt$star[0] : "";
  var unique = $staropt$star$1 ? $staropt$star$1[0] : "";
  return Vdom.fullnode("", "img", key, unique, props, nodes);
}

function select($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star ? $staropt$star[0] : "";
  var unique = $staropt$star$1 ? $staropt$star$1[0] : "";
  return Vdom.fullnode("", "select", key, unique, props, nodes);
}

function option$prime($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star ? $staropt$star[0] : "";
  var unique = $staropt$star$1 ? $staropt$star$1[0] : "";
  return Vdom.fullnode("", "option", key, unique, props, nodes);
}

function form($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star ? $staropt$star[0] : "";
  var unique = $staropt$star$1 ? $staropt$star$1[0] : "";
  return Vdom.fullnode("", "form", key, unique, props, nodes);
}

function nav($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star ? $staropt$star[0] : "";
  var unique = $staropt$star$1 ? $staropt$star$1[0] : "";
  return Vdom.fullnode("", "nav", key, unique, props, nodes);
}

function main($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star ? $staropt$star[0] : "";
  var unique = $staropt$star$1 ? $staropt$star$1[0] : "";
  return Vdom.fullnode("", "main", key, unique, props, nodes);
}

function id(str) {
  return /* RawProp */Block.__(0, [
            "id",
            str
          ]);
}

function href(str) {
  return /* RawProp */Block.__(0, [
            "href",
            str
          ]);
}

function src(str) {
  return /* RawProp */Block.__(0, [
            "src",
            str
          ]);
}

function class$prime(name) {
  return /* RawProp */Block.__(0, [
            "className",
            name
          ]);
}

function classList(classes) {
  var name = $$String.concat(" ", List.map((function (param) {
              return param[0];
            }), List.filter((function (param) {
                    return param[1];
                  }))(classes)));
  return /* RawProp */Block.__(0, [
            "className",
            name
          ]);
}

function type$prime(typ) {
  return /* RawProp */Block.__(0, [
            "type",
            typ
          ]);
}

var style = Vdom.style;

function styles(s) {
  return /* Style */Block.__(4, [s]);
}

function placeholder(str) {
  return /* RawProp */Block.__(0, [
            "placeholder",
            str
          ]);
}

function autofocus(b) {
  if (b) {
    return /* RawProp */Block.__(0, [
              "autofocus",
              "autofocus"
            ]);
  } else {
    return /* NoProp */0;
  }
}

function value(str) {
  return /* RawProp */Block.__(0, [
            "value",
            str
          ]);
}

function name(str) {
  return /* RawProp */Block.__(0, [
            "name",
            str
          ]);
}

function checked(b) {
  if (b) {
    return /* RawProp */Block.__(0, [
              "checked",
              "checked"
            ]);
  } else {
    return /* NoProp */0;
  }
}

function for$prime(str) {
  return /* RawProp */Block.__(0, [
            "htmlFor",
            str
          ]);
}

function hidden(b) {
  if (b) {
    return /* RawProp */Block.__(0, [
              "hidden",
              "hidden"
            ]);
  } else {
    return /* NoProp */0;
  }
}

function target(t) {
  return /* RawProp */Block.__(0, [
            "target",
            t
          ]);
}

function action(a) {
  return /* RawProp */Block.__(0, [
            "action",
            a
          ]);
}

function method$prime(m) {
  return /* RawProp */Block.__(0, [
            "method",
            m
          ]);
}

var onCB = Vdom.onCB;

var onMsg = Vdom.onMsg;

function onInputOpt($staropt$star, msg) {
  var key = $staropt$star ? $staropt$star[0] : "";
  return Vdom.onCB("input", key, (function (ev) {
                var match = ev.target;
                if (match !== undefined) {
                  var match$1 = match.value;
                  if (match$1 !== undefined) {
                    return Curry._1(msg, match$1);
                  } else {
                    return /* None */0;
                  }
                } else {
                  return /* None */0;
                }
              }));
}

function onInput($staropt$star, msg) {
  var key = $staropt$star ? $staropt$star[0] : "";
  return onInputOpt(/* Some */[key], (function (ev) {
                return /* Some */[Curry._1(msg, ev)];
              }));
}

function onChangeOpt($staropt$star, msg) {
  var key = $staropt$star ? $staropt$star[0] : "";
  return Vdom.onCB("change", key, (function (ev) {
                var match = ev.target;
                if (match !== undefined) {
                  var match$1 = match.value;
                  if (match$1 !== undefined) {
                    return Curry._1(msg, match$1);
                  } else {
                    return /* None */0;
                  }
                } else {
                  return /* None */0;
                }
              }));
}

function onChange($staropt$star, msg) {
  var key = $staropt$star ? $staropt$star[0] : "";
  return onChangeOpt(/* Some */[key], (function (ev) {
                return /* Some */[Curry._1(msg, ev)];
              }));
}

function onClick(msg) {
  return Vdom.onMsg("click", msg);
}

function onDoubleClick(msg) {
  return Vdom.onMsg("dblclick", msg);
}

function onBlur(msg) {
  return Vdom.onMsg("blur", msg);
}

function onFocus(msg) {
  return Vdom.onMsg("focus", msg);
}

function onCheckOpt($staropt$star, msg) {
  var key = $staropt$star ? $staropt$star[0] : "";
  return Vdom.onCB("change", key, (function (ev) {
                var match = ev.target;
                if (match !== undefined) {
                  var match$1 = match.checked;
                  if (match$1 !== undefined) {
                    return Curry._1(msg, match$1);
                  } else {
                    return /* None */0;
                  }
                } else {
                  return /* None */0;
                }
              }));
}

function onCheck($staropt$star, msg) {
  var key = $staropt$star ? $staropt$star[0] : "";
  return onCheckOpt(/* Some */[key], (function (ev) {
                return /* Some */[Curry._1(msg, ev)];
              }));
}

function onMouseDown(msg) {
  return Vdom.onMsg("mousedown", msg);
}

function onMouseUp(msg) {
  return Vdom.onMsg("mouseup", msg);
}

function onMouseEnter(msg) {
  return Vdom.onMsg("mouseenter", msg);
}

function onMouseLeave(msg) {
  return Vdom.onMsg("mouseleave", msg);
}

function onMouseOver(msg) {
  return Vdom.onMsg("mouseover", msg);
}

function onMouseOut(msg) {
  return Vdom.onMsg("mouseout", msg);
}

function max(value) {
  return /* Attribute */Block.__(1, [
            "",
            "max",
            value
          ]);
}

function min(value) {
  return /* Attribute */Block.__(1, [
            "",
            "min",
            value
          ]);
}

function step(value) {
  return /* Attribute */Block.__(1, [
            "",
            "step",
            value
          ]);
}

function disabled(b) {
  if (b) {
    return /* Attribute */Block.__(1, [
              "",
              "disabled",
              "true"
            ]);
  } else {
    return /* NoProp */0;
  }
}

function selected(b) {
  if (b) {
    return /* Attribute */Block.__(1, [
              "",
              "selected",
              "true"
            ]);
  } else {
    return /* NoProp */0;
  }
}

function acceptCharset(c) {
  return /* Attribute */Block.__(1, [
            "",
            "accept-charset",
            c
          ]);
}

var Attributes = /* module */[
  /* max */max,
  /* min */min,
  /* step */step,
  /* disabled */disabled,
  /* selected */selected,
  /* acceptCharset */acceptCharset
];

var Cmds = 0;

var noNode = Vdom.noNode;

var noProp = /* NoProp */0;

exports.Cmds          = Cmds;
exports.noNode        = noNode;
exports.text          = text;
exports.lazy1         = lazy1;
exports.node          = node;
exports.br            = br;
exports.br$prime      = br$prime;
exports.div           = div;
exports.span          = span;
exports.p             = p;
exports.pre           = pre;
exports.a             = a;
exports.section       = section;
exports.header        = header;
exports.footer        = footer;
exports.h1            = h1;
exports.h2            = h2;
exports.h3            = h3;
exports.h4            = h4;
exports.h5            = h5;
exports.h6            = h6;
exports.i             = i;
exports.strong        = strong;
exports.button        = button;
exports.input$prime   = input$prime;
exports.textarea      = textarea;
exports.label         = label;
exports.ul            = ul;
exports.ol            = ol;
exports.li            = li;
exports.table         = table;
exports.thead         = thead;
exports.tfoot         = tfoot;
exports.tbody         = tbody;
exports.th            = th;
exports.tr            = tr;
exports.td            = td;
exports.progress      = progress;
exports.img           = img;
exports.select        = select;
exports.option$prime  = option$prime;
exports.form          = form;
exports.nav           = nav;
exports.main          = main;
exports.noProp        = noProp;
exports.id            = id;
exports.href          = href;
exports.src           = src;
exports.class$prime   = class$prime;
exports.classList     = classList;
exports.type$prime    = type$prime;
exports.style         = style;
exports.styles        = styles;
exports.placeholder   = placeholder;
exports.autofocus     = autofocus;
exports.value         = value;
exports.name          = name;
exports.checked       = checked;
exports.for$prime     = for$prime;
exports.hidden        = hidden;
exports.target        = target;
exports.action        = action;
exports.method$prime  = method$prime;
exports.onCB          = onCB;
exports.onMsg         = onMsg;
exports.onInputOpt    = onInputOpt;
exports.onInput       = onInput;
exports.onChangeOpt   = onChangeOpt;
exports.onChange      = onChange;
exports.onClick       = onClick;
exports.onDoubleClick = onDoubleClick;
exports.onBlur        = onBlur;
exports.onFocus       = onFocus;
exports.onCheckOpt    = onCheckOpt;
exports.onCheck       = onCheck;
exports.onMouseDown   = onMouseDown;
exports.onMouseUp     = onMouseUp;
exports.onMouseEnter  = onMouseEnter;
exports.onMouseLeave  = onMouseLeave;
exports.onMouseOver   = onMouseOver;
exports.onMouseOut    = onMouseOut;
exports.Attributes    = Attributes;
/* No side effect */
