// Generated by BUCKLESCRIPT VERSION 1.4.1 , PLEASE EDIT WITH CARE
'use strict';

var Js_primitive = require("bs-platform/lib/js/js_primitive");
var Block        = require("bs-platform/lib/js/block");
var Web          = require("./web");
var Tea_cmd      = require("./tea_cmd");

function focus(id) {
  return /* EnqueueCall */Block.__(2, [function () {
              var match = document.getElementById(id);
              if (Js_primitive.js_is_nil_undef(match)) {
                console.log(/* tuple */[
                      "Attempted to focus a non-existant element of: ",
                      id
                    ]);
                return /* () */0;
              }
              else {
                var ecb = function () {
                  return match.focus();
                };
                var cb = function () {
                  window.requestAnimationFrame(ecb);
                  return /* () */0;
                };
                window.requestAnimationFrame(cb);
                return /* () */0;
              }
            }]);
}

exports.focus = focus;
/* Web Not a pure module */
