// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var Caml_option = require("rescript/lib/js/caml_option.js");

function cmd(promise, tagger) {
  return {
          TAG: /* EnqueueCall */2,
          _0: (function (x) {
              promise.then(function (x$1) {
                    var msg = Curry._1(tagger, x$1);
                    if (msg !== undefined) {
                      Curry._1(x.contents.enqueue, Caml_option.valFromOption(msg));
                      return Promise.resolve(undefined);
                    } else {
                      return Promise.resolve(undefined);
                    }
                  });
              
            })
        };
}

function result(promise, msg) {
  return {
          TAG: /* EnqueueCall */2,
          _0: (function (x) {
              var enq = function (result) {
                return Curry._1(x.contents.enqueue, Curry._1(msg, result));
              };
              promise.then(function (x) {
                      return Promise.resolve(enq({
                                      TAG: /* Ok */0,
                                      _0: x
                                    }));
                    }).catch(function (x) {
                    return Promise.resolve(enq({
                                    TAG: /* Error */1,
                                    _0: "" + x
                                  }));
                  });
              
            })
        };
}

exports.cmd = cmd;
exports.result = result;
/* No side effect */
