// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function accentHeight(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "accent-height",
          _2: v
        };
}

function accelerate(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "accelerate",
          _2: v
        };
}

function accumulate(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "accumulate",
          _2: v
        };
}

function additive(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "additive",
          _2: v
        };
}

function alphabetic(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "alphabetic",
          _2: v
        };
}

function allowReorder(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "allowReorder",
          _2: v
        };
}

function amplitude(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "amplitude",
          _2: v
        };
}

function arabicForm(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "arabic-form",
          _2: v
        };
}

function ascent(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "ascent",
          _2: v
        };
}

function attributeName(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "attributeName",
          _2: v
        };
}

function attributeType(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "attributeType",
          _2: v
        };
}

function autoReverse(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "autoReverse",
          _2: v
        };
}

function azimuth(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "azimuth",
          _2: v
        };
}

function baseFrequency(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "baseFrequency",
          _2: v
        };
}

function baseProfile(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "baseProfile",
          _2: v
        };
}

function bbox(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "bbox",
          _2: v
        };
}

function begin$p(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "begin",
          _2: v
        };
}

function bias(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "bias",
          _2: v
        };
}

function by(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "by",
          _2: v
        };
}

function calcMode(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "calcMode",
          _2: v
        };
}

function capHeight(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "cap-height",
          _2: v
        };
}

function class$p(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "class",
          _2: v
        };
}

function clipPathUnits(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "clipPathUnits",
          _2: v
        };
}

function contentScriptType(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "contentScriptType",
          _2: v
        };
}

function contentStyleType(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "contentStyleType",
          _2: v
        };
}

function cx(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "cx",
          _2: v
        };
}

function cy(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "cy",
          _2: v
        };
}

function d(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "d",
          _2: v
        };
}

function decelerate(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "decelerate",
          _2: v
        };
}

function descent(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "descent",
          _2: v
        };
}

function diffuseConstant(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "diffuseConstant",
          _2: v
        };
}

function divisor(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "divisor",
          _2: v
        };
}

function dur(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "dur",
          _2: v
        };
}

function dx(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "dx",
          _2: v
        };
}

function dy(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "dy",
          _2: v
        };
}

function edgeMode(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "edgeMode",
          _2: v
        };
}

function elevation(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "elevation",
          _2: v
        };
}

function end$p(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "end",
          _2: v
        };
}

function exponent(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "exponent",
          _2: v
        };
}

function externalResourcesRequired(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "externalResourcesRequired",
          _2: v
        };
}

function filterRes(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "filterRes",
          _2: v
        };
}

function filterUnits(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "filterUnits",
          _2: v
        };
}

function format(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "format",
          _2: v
        };
}

function from(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "from",
          _2: v
        };
}

function fx(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "fx",
          _2: v
        };
}

function fy(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "fy",
          _2: v
        };
}

function g1(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "g1",
          _2: v
        };
}

function g2(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "g2",
          _2: v
        };
}

function glyphName(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "glyph-name",
          _2: v
        };
}

function glyphRef(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "glyphRef",
          _2: v
        };
}

function gradientTransform(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "gradientTransform",
          _2: v
        };
}

function gradientUnits(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "gradientUnits",
          _2: v
        };
}

function hanging(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "hanging",
          _2: v
        };
}

function height(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "height",
          _2: v
        };
}

function horizAdvX(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "horiz-adv-x",
          _2: v
        };
}

function horizOriginX(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "horiz-origin-x",
          _2: v
        };
}

function horizOriginY(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "horiz-origin-y",
          _2: v
        };
}

function id(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "id",
          _2: v
        };
}

function ideographic(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "ideographic",
          _2: v
        };
}

function in$p(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "in",
          _2: v
        };
}

function in2(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "in2",
          _2: v
        };
}

function intercept(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "intercept",
          _2: v
        };
}

function k(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "k",
          _2: v
        };
}

function k1(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "k1",
          _2: v
        };
}

function k2(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "k2",
          _2: v
        };
}

function k3(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "k3",
          _2: v
        };
}

function k4(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "k4",
          _2: v
        };
}

function kernelMatrix(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "kernelMatrix",
          _2: v
        };
}

function kernelUnitLength(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "kernelUnitLength",
          _2: v
        };
}

function keyPoints(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "keyPoints",
          _2: v
        };
}

function keySplines(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "keySplines",
          _2: v
        };
}

function keyTimes(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "keyTimes",
          _2: v
        };
}

function lang(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "lang",
          _2: v
        };
}

function lengthAdjust(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "lengthAdjust",
          _2: v
        };
}

function limitingConeAngle(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "limitingConeAngle",
          _2: v
        };
}

function local(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "local",
          _2: v
        };
}

function markerHeight(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "markerHeight",
          _2: v
        };
}

function markerUnits(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "markerUnits",
          _2: v
        };
}

function markerWidth(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "markerWidth",
          _2: v
        };
}

function maskContentUnits(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "maskContentUnits",
          _2: v
        };
}

function maskUnits(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "maskUnits",
          _2: v
        };
}

function mathematical(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "mathematical",
          _2: v
        };
}

function max(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "max",
          _2: v
        };
}

function media(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "media",
          _2: v
        };
}

function method$p(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "method",
          _2: v
        };
}

function min(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "min",
          _2: v
        };
}

function mode(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "mode",
          _2: v
        };
}

function name(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "name",
          _2: v
        };
}

function numOctaves(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "numOctaves",
          _2: v
        };
}

function offset(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "offset",
          _2: v
        };
}

function operator(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "operator",
          _2: v
        };
}

function order(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "order",
          _2: v
        };
}

function orient(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "orient",
          _2: v
        };
}

function orientation(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "orientation",
          _2: v
        };
}

function origin(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "origin",
          _2: v
        };
}

function overlinePosition(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "overline-position",
          _2: v
        };
}

function overlineThickness(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "overline-thickness",
          _2: v
        };
}

function panose1(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "panose-1",
          _2: v
        };
}

function path(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "path",
          _2: v
        };
}

function pathLength(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "pathLength",
          _2: v
        };
}

function patternContentUnits(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "patternContentUnits",
          _2: v
        };
}

function patternTransform(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "patternTransform",
          _2: v
        };
}

function patternUnits(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "patternUnits",
          _2: v
        };
}

function pointOrder(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "point-order",
          _2: v
        };
}

function points(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "points",
          _2: v
        };
}

function pointsAtX(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "pointsAtX",
          _2: v
        };
}

function pointsAtY(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "pointsAtY",
          _2: v
        };
}

function pointsAtZ(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "pointsAtZ",
          _2: v
        };
}

function preserveAlpha(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "preserveAlpha",
          _2: v
        };
}

function preserveAspectRatio(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "preserveAspectRatio",
          _2: v
        };
}

function primitiveUnits(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "primitiveUnits",
          _2: v
        };
}

function r(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "r",
          _2: v
        };
}

function radius(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "radius",
          _2: v
        };
}

function refX(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "refX",
          _2: v
        };
}

function refY(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "refY",
          _2: v
        };
}

function renderingIntent(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "rendering-intent",
          _2: v
        };
}

function repeatCount(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "repeatCount",
          _2: v
        };
}

function repeatDur(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "repeatDur",
          _2: v
        };
}

function requiredExtensions(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "requiredExtensions",
          _2: v
        };
}

function requiredFeatures(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "requiredFeatures",
          _2: v
        };
}

function restart(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "restart",
          _2: v
        };
}

function result(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "result",
          _2: v
        };
}

function rotate(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "rotate",
          _2: v
        };
}

function rx(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "rx",
          _2: v
        };
}

function ry(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "ry",
          _2: v
        };
}

function scale(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "scale",
          _2: v
        };
}

function seed(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "seed",
          _2: v
        };
}

function slope(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "slope",
          _2: v
        };
}

function spacing(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "spacing",
          _2: v
        };
}

function specularConstant(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "specularConstant",
          _2: v
        };
}

function specularExponent(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "specularExponent",
          _2: v
        };
}

function speed(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "speed",
          _2: v
        };
}

function spreadMethod(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "spreadMethod",
          _2: v
        };
}

function startOffset(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "startOffset",
          _2: v
        };
}

function stdDeviation(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "stdDeviation",
          _2: v
        };
}

function stemh(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "stemh",
          _2: v
        };
}

function stemv(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "stemv",
          _2: v
        };
}

function stitchTiles(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "stitchTiles",
          _2: v
        };
}

function strikethroughPosition(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "strikethrough-position",
          _2: v
        };
}

function strikethroughThickness(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "strikethrough-thickness",
          _2: v
        };
}

function string(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "string",
          _2: v
        };
}

function style(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "style",
          _2: v
        };
}

function surfaceScale(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "surfaceScale",
          _2: v
        };
}

function systemLanguage(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "systemLanguage",
          _2: v
        };
}

function tableValues(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "tableValues",
          _2: v
        };
}

function target(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "target",
          _2: v
        };
}

function targetX(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "targetX",
          _2: v
        };
}

function targetY(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "targetY",
          _2: v
        };
}

function textLength(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "textLength",
          _2: v
        };
}

function title(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "title",
          _2: v
        };
}

function to$p(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "to",
          _2: v
        };
}

function transform(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "transform",
          _2: v
        };
}

function type$p(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "type",
          _2: v
        };
}

function u1(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "u1",
          _2: v
        };
}

function u2(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "u2",
          _2: v
        };
}

function underlinePosition(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "underline-position",
          _2: v
        };
}

function underlineThickness(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "underline-thickness",
          _2: v
        };
}

function unicode(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "unicode",
          _2: v
        };
}

function unicodeRange(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "unicode-range",
          _2: v
        };
}

function unitsPerEm(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "units-per-em",
          _2: v
        };
}

function vAlphabetic(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "v-alphabetic",
          _2: v
        };
}

function vHanging(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "v-hanging",
          _2: v
        };
}

function vIdeographic(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "v-ideographic",
          _2: v
        };
}

function vMathematical(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "v-mathematical",
          _2: v
        };
}

function values(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "values",
          _2: v
        };
}

function version(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "version",
          _2: v
        };
}

function vertAdvY(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "vert-adv-y",
          _2: v
        };
}

function vertOriginX(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "vert-origin-x",
          _2: v
        };
}

function vertOriginY(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "vert-origin-y",
          _2: v
        };
}

function viewBox(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "viewBox",
          _2: v
        };
}

function viewTarget(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "viewTarget",
          _2: v
        };
}

function width(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "width",
          _2: v
        };
}

function widths(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "widths",
          _2: v
        };
}

function x(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "x",
          _2: v
        };
}

function xHeight(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "x-height",
          _2: v
        };
}

function x1(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "x1",
          _2: v
        };
}

function x2(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "x2",
          _2: v
        };
}

function xChannelSelector(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "xChannelSelector",
          _2: v
        };
}

function xlinkActuate(v) {
  return {
          TAG: /* Attribute */1,
          _0: "http://www.w3.org/1999/xlink",
          _1: "xlink:actuate",
          _2: v
        };
}

function xlinkArcrole(v) {
  return {
          TAG: /* Attribute */1,
          _0: "http://www.w3.org/1999/xlink",
          _1: "xlink:arcrole",
          _2: v
        };
}

function xlinkHref(v) {
  return {
          TAG: /* Attribute */1,
          _0: "http://www.w3.org/1999/xlink",
          _1: "xlink:href",
          _2: v
        };
}

function xlinkRole(v) {
  return {
          TAG: /* Attribute */1,
          _0: "http://www.w3.org/1999/xlink",
          _1: "xlink:role",
          _2: v
        };
}

function xlinkShow(v) {
  return {
          TAG: /* Attribute */1,
          _0: "http://www.w3.org/1999/xlink",
          _1: "xlink:show",
          _2: v
        };
}

function xlinkTitle(v) {
  return {
          TAG: /* Attribute */1,
          _0: "http://www.w3.org/1999/xlink",
          _1: "xlink:title",
          _2: v
        };
}

function xlinkType(v) {
  return {
          TAG: /* Attribute */1,
          _0: "http://www.w3.org/1999/xlink",
          _1: "xlink:type",
          _2: v
        };
}

function xmlBase(v) {
  return {
          TAG: /* Attribute */1,
          _0: "http://www.w3.org/XML/1998/namespace",
          _1: "xml:base",
          _2: v
        };
}

function xmlLang(v) {
  return {
          TAG: /* Attribute */1,
          _0: "http://www.w3.org/XML/1998/namespace",
          _1: "xml:lang",
          _2: v
        };
}

function xmlSpace(v) {
  return {
          TAG: /* Attribute */1,
          _0: "http://www.w3.org/XML/1998/namespace",
          _1: "xml:space",
          _2: v
        };
}

function y(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "y",
          _2: v
        };
}

function y1(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "y1",
          _2: v
        };
}

function y2(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "y2",
          _2: v
        };
}

function yChannelSelector(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "yChannelSelector",
          _2: v
        };
}

function z(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "z",
          _2: v
        };
}

function zoomAndPan(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "zoomAndPan",
          _2: v
        };
}

function alignmentBaseline(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "alignment-baseline",
          _2: v
        };
}

function baselineShift(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "baseline-shift",
          _2: v
        };
}

function clipPath(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "clip-path",
          _2: v
        };
}

function clipRule(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "clip-rule",
          _2: v
        };
}

function clip(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "clip",
          _2: v
        };
}

function colorInterpolationFilters(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "color-interpolation-filters",
          _2: v
        };
}

function colorInterpolation(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "color-interpolation",
          _2: v
        };
}

function colorProfile(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "color-profile",
          _2: v
        };
}

function colorRendering(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "color-rendering",
          _2: v
        };
}

function color(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "color",
          _2: v
        };
}

function cursor(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "cursor",
          _2: v
        };
}

function direction(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "direction",
          _2: v
        };
}

function display(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "display",
          _2: v
        };
}

function dominantBaseline(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "dominant-baseline",
          _2: v
        };
}

function enableBackground(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "enable-background",
          _2: v
        };
}

function fillOpacity(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "fill-opacity",
          _2: v
        };
}

function fillRule(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "fill-rule",
          _2: v
        };
}

function fill(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "fill",
          _2: v
        };
}

function filter(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "filter",
          _2: v
        };
}

function floodColor(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "flood-color",
          _2: v
        };
}

function floodOpacity(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "flood-opacity",
          _2: v
        };
}

function fontFamily(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "font-family",
          _2: v
        };
}

function fontSizeAdjust(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "font-size-adjust",
          _2: v
        };
}

function fontSize(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "font-size",
          _2: v
        };
}

function fontStretch(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "font-stretch",
          _2: v
        };
}

function fontStyle(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "font-style",
          _2: v
        };
}

function fontVariant(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "font-variant",
          _2: v
        };
}

function fontWeight(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "font-weight",
          _2: v
        };
}

function glyphOrientationHorizontal(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "glyph-orientation-horizontal",
          _2: v
        };
}

function glyphOrientationVertical(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "glyph-orientation-vertical",
          _2: v
        };
}

function imageRendering(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "image-rendering",
          _2: v
        };
}

function kerning(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "kerning",
          _2: v
        };
}

function letterSpacing(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "letter-spacing",
          _2: v
        };
}

function lightingColor(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "lighting-color",
          _2: v
        };
}

function markerEnd(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "marker-end",
          _2: v
        };
}

function markerMid(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "marker-mid",
          _2: v
        };
}

function markerStart(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "marker-start",
          _2: v
        };
}

function mask(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "mask",
          _2: v
        };
}

function opacity(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "opacity",
          _2: v
        };
}

function overflow(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "overflow",
          _2: v
        };
}

function pointerEvents(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "pointer-events",
          _2: v
        };
}

function shapeRendering(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "shape-rendering",
          _2: v
        };
}

function stopColor(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "stop-color",
          _2: v
        };
}

function stopOpacity(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "stop-opacity",
          _2: v
        };
}

function strokeDasharray(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "stroke-dasharray",
          _2: v
        };
}

function strokeDashoffset(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "stroke-dashoffset",
          _2: v
        };
}

function strokeLinecap(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "stroke-linecap",
          _2: v
        };
}

function strokeLinejoin(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "stroke-linejoin",
          _2: v
        };
}

function strokeMiterlimit(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "stroke-miterlimit",
          _2: v
        };
}

function strokeOpacity(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "stroke-opacity",
          _2: v
        };
}

function strokeWidth(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "stroke-width",
          _2: v
        };
}

function stroke(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "stroke",
          _2: v
        };
}

function textAnchor(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "text-anchor",
          _2: v
        };
}

function textDecoration(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "text-decoration",
          _2: v
        };
}

function textRendering(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "text-rendering",
          _2: v
        };
}

function unicodeBidi(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "unicode-bidi",
          _2: v
        };
}

function visibility(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "visibility",
          _2: v
        };
}

function wordSpacing(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "word-spacing",
          _2: v
        };
}

function writingMode(v) {
  return {
          TAG: /* Attribute */1,
          _0: "",
          _1: "writing-mode",
          _2: v
        };
}

exports.accentHeight = accentHeight;
exports.accelerate = accelerate;
exports.accumulate = accumulate;
exports.additive = additive;
exports.alphabetic = alphabetic;
exports.allowReorder = allowReorder;
exports.amplitude = amplitude;
exports.arabicForm = arabicForm;
exports.ascent = ascent;
exports.attributeName = attributeName;
exports.attributeType = attributeType;
exports.autoReverse = autoReverse;
exports.azimuth = azimuth;
exports.baseFrequency = baseFrequency;
exports.baseProfile = baseProfile;
exports.bbox = bbox;
exports.begin$p = begin$p;
exports.bias = bias;
exports.by = by;
exports.calcMode = calcMode;
exports.capHeight = capHeight;
exports.class$p = class$p;
exports.clipPathUnits = clipPathUnits;
exports.contentScriptType = contentScriptType;
exports.contentStyleType = contentStyleType;
exports.cx = cx;
exports.cy = cy;
exports.d = d;
exports.decelerate = decelerate;
exports.descent = descent;
exports.diffuseConstant = diffuseConstant;
exports.divisor = divisor;
exports.dur = dur;
exports.dx = dx;
exports.dy = dy;
exports.edgeMode = edgeMode;
exports.elevation = elevation;
exports.end$p = end$p;
exports.exponent = exponent;
exports.externalResourcesRequired = externalResourcesRequired;
exports.filterRes = filterRes;
exports.filterUnits = filterUnits;
exports.format = format;
exports.from = from;
exports.fx = fx;
exports.fy = fy;
exports.g1 = g1;
exports.g2 = g2;
exports.glyphName = glyphName;
exports.glyphRef = glyphRef;
exports.gradientTransform = gradientTransform;
exports.gradientUnits = gradientUnits;
exports.hanging = hanging;
exports.height = height;
exports.horizAdvX = horizAdvX;
exports.horizOriginX = horizOriginX;
exports.horizOriginY = horizOriginY;
exports.id = id;
exports.ideographic = ideographic;
exports.in$p = in$p;
exports.in2 = in2;
exports.intercept = intercept;
exports.k = k;
exports.k1 = k1;
exports.k2 = k2;
exports.k3 = k3;
exports.k4 = k4;
exports.kernelMatrix = kernelMatrix;
exports.kernelUnitLength = kernelUnitLength;
exports.keyPoints = keyPoints;
exports.keySplines = keySplines;
exports.keyTimes = keyTimes;
exports.lang = lang;
exports.lengthAdjust = lengthAdjust;
exports.limitingConeAngle = limitingConeAngle;
exports.local = local;
exports.markerHeight = markerHeight;
exports.markerUnits = markerUnits;
exports.markerWidth = markerWidth;
exports.maskContentUnits = maskContentUnits;
exports.maskUnits = maskUnits;
exports.mathematical = mathematical;
exports.max = max;
exports.media = media;
exports.method$p = method$p;
exports.min = min;
exports.mode = mode;
exports.name = name;
exports.numOctaves = numOctaves;
exports.offset = offset;
exports.operator = operator;
exports.order = order;
exports.orient = orient;
exports.orientation = orientation;
exports.origin = origin;
exports.overlinePosition = overlinePosition;
exports.overlineThickness = overlineThickness;
exports.panose1 = panose1;
exports.path = path;
exports.pathLength = pathLength;
exports.patternContentUnits = patternContentUnits;
exports.patternTransform = patternTransform;
exports.patternUnits = patternUnits;
exports.pointOrder = pointOrder;
exports.points = points;
exports.pointsAtX = pointsAtX;
exports.pointsAtY = pointsAtY;
exports.pointsAtZ = pointsAtZ;
exports.preserveAlpha = preserveAlpha;
exports.preserveAspectRatio = preserveAspectRatio;
exports.primitiveUnits = primitiveUnits;
exports.r = r;
exports.radius = radius;
exports.refX = refX;
exports.refY = refY;
exports.renderingIntent = renderingIntent;
exports.repeatCount = repeatCount;
exports.repeatDur = repeatDur;
exports.requiredExtensions = requiredExtensions;
exports.requiredFeatures = requiredFeatures;
exports.restart = restart;
exports.result = result;
exports.rotate = rotate;
exports.rx = rx;
exports.ry = ry;
exports.scale = scale;
exports.seed = seed;
exports.slope = slope;
exports.spacing = spacing;
exports.specularConstant = specularConstant;
exports.specularExponent = specularExponent;
exports.speed = speed;
exports.spreadMethod = spreadMethod;
exports.startOffset = startOffset;
exports.stdDeviation = stdDeviation;
exports.stemh = stemh;
exports.stemv = stemv;
exports.stitchTiles = stitchTiles;
exports.strikethroughPosition = strikethroughPosition;
exports.strikethroughThickness = strikethroughThickness;
exports.string = string;
exports.style = style;
exports.surfaceScale = surfaceScale;
exports.systemLanguage = systemLanguage;
exports.tableValues = tableValues;
exports.target = target;
exports.targetX = targetX;
exports.targetY = targetY;
exports.textLength = textLength;
exports.title = title;
exports.to$p = to$p;
exports.transform = transform;
exports.type$p = type$p;
exports.u1 = u1;
exports.u2 = u2;
exports.underlinePosition = underlinePosition;
exports.underlineThickness = underlineThickness;
exports.unicode = unicode;
exports.unicodeRange = unicodeRange;
exports.unitsPerEm = unitsPerEm;
exports.vAlphabetic = vAlphabetic;
exports.vHanging = vHanging;
exports.vIdeographic = vIdeographic;
exports.vMathematical = vMathematical;
exports.values = values;
exports.version = version;
exports.vertAdvY = vertAdvY;
exports.vertOriginX = vertOriginX;
exports.vertOriginY = vertOriginY;
exports.viewBox = viewBox;
exports.viewTarget = viewTarget;
exports.width = width;
exports.widths = widths;
exports.x = x;
exports.xHeight = xHeight;
exports.x1 = x1;
exports.x2 = x2;
exports.xChannelSelector = xChannelSelector;
exports.xlinkActuate = xlinkActuate;
exports.xlinkArcrole = xlinkArcrole;
exports.xlinkHref = xlinkHref;
exports.xlinkRole = xlinkRole;
exports.xlinkShow = xlinkShow;
exports.xlinkTitle = xlinkTitle;
exports.xlinkType = xlinkType;
exports.xmlBase = xmlBase;
exports.xmlLang = xmlLang;
exports.xmlSpace = xmlSpace;
exports.y = y;
exports.y1 = y1;
exports.y2 = y2;
exports.yChannelSelector = yChannelSelector;
exports.z = z;
exports.zoomAndPan = zoomAndPan;
exports.alignmentBaseline = alignmentBaseline;
exports.baselineShift = baselineShift;
exports.clipPath = clipPath;
exports.clipRule = clipRule;
exports.clip = clip;
exports.colorInterpolationFilters = colorInterpolationFilters;
exports.colorInterpolation = colorInterpolation;
exports.colorProfile = colorProfile;
exports.colorRendering = colorRendering;
exports.color = color;
exports.cursor = cursor;
exports.direction = direction;
exports.display = display;
exports.dominantBaseline = dominantBaseline;
exports.enableBackground = enableBackground;
exports.fillOpacity = fillOpacity;
exports.fillRule = fillRule;
exports.fill = fill;
exports.filter = filter;
exports.floodColor = floodColor;
exports.floodOpacity = floodOpacity;
exports.fontFamily = fontFamily;
exports.fontSizeAdjust = fontSizeAdjust;
exports.fontSize = fontSize;
exports.fontStretch = fontStretch;
exports.fontStyle = fontStyle;
exports.fontVariant = fontVariant;
exports.fontWeight = fontWeight;
exports.glyphOrientationHorizontal = glyphOrientationHorizontal;
exports.glyphOrientationVertical = glyphOrientationVertical;
exports.imageRendering = imageRendering;
exports.kerning = kerning;
exports.letterSpacing = letterSpacing;
exports.lightingColor = lightingColor;
exports.markerEnd = markerEnd;
exports.markerMid = markerMid;
exports.markerStart = markerStart;
exports.mask = mask;
exports.opacity = opacity;
exports.overflow = overflow;
exports.pointerEvents = pointerEvents;
exports.shapeRendering = shapeRendering;
exports.stopColor = stopColor;
exports.stopOpacity = stopOpacity;
exports.strokeDasharray = strokeDasharray;
exports.strokeDashoffset = strokeDashoffset;
exports.strokeLinecap = strokeLinecap;
exports.strokeLinejoin = strokeLinejoin;
exports.strokeMiterlimit = strokeMiterlimit;
exports.strokeOpacity = strokeOpacity;
exports.strokeWidth = strokeWidth;
exports.stroke = stroke;
exports.textAnchor = textAnchor;
exports.textDecoration = textDecoration;
exports.textRendering = textRendering;
exports.unicodeBidi = unicodeBidi;
exports.visibility = visibility;
exports.wordSpacing = wordSpacing;
exports.writingMode = writingMode;
/* No side effect */
