// Generated by BUCKLESCRIPT VERSION 1.5.2, PLEASE EDIT WITH CARE
'use strict';

var Block                   = require("bs-platform/lib/js/block");
var Curry                   = require("bs-platform/lib/js/curry");
var Web_window_localstorage = require("./web_window_localstorage");

function getItem(key) {
  return /* Task */[function (cb) {
            var match = Web_window_localstorage.getItem(window, key);
            if (match) {
              return Curry._1(cb, /* Ok */Block.__(0, [match[0]]));
            }
            else {
              return Curry._1(cb, /* Error */Block.__(1, ["Key not found"]));
            }
          }];
}

function setItem(key, value) {
  return /* Task */[function (cb) {
            Web_window_localstorage.setItem(window, key, value);
            return Curry._1(cb, /* Ok */Block.__(0, [/* () */0]));
          }];
}

var LocalStorage = /* module */[
  /* getItem */getItem,
  /* setItem */setItem
];

exports.LocalStorage = LocalStorage;
/* No side effect */
