// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Web = require("./web.js");
var List = require("rescript/lib/js/list.js");
var Vdom = require("./vdom.js");
var Curry = require("rescript/lib/js/curry.js");
var Tea_cmd = require("./tea_cmd.js");
var Tea_sub = require("./tea_sub.js");
var Caml_option = require("rescript/lib/js/caml_option.js");

function programStateWrapper(initModel, pump, shutdown) {
  var model = {
    contents: initModel
  };
  var callbacks = {
    contents: {
      enqueue: (function (_msg) {
          console.log("INVALID enqueue CALL!");
          
        }),
      on: (function (param) {
          
        })
    }
  };
  var pumperInterface = Curry._1(pump, callbacks);
  var pending = {
    contents: undefined
  };
  var handler = function (msg) {
    var msgs = pending.contents;
    if (msgs !== undefined) {
      pending.contents = {
        hd: msg,
        tl: msgs
      };
      return ;
    }
    pending.contents = /* [] */0;
    var newModel = Curry._2(pumperInterface.handleMsg, model.contents, msg);
    model.contents = newModel;
    var msgs$1 = pending.contents;
    if (msgs$1 !== undefined) {
      if (msgs$1) {
        pending.contents = undefined;
        return List.iter(handler, List.rev(msgs$1));
      } else {
        pending.contents = undefined;
        return ;
      }
    }
    throw {
          RE_EXN_ID: "Failure",
          _1: "INVALID message queue state, should never be None during message processing!",
          Error: new Error()
        };
  };
  var render_events = {
    contents: /* [] */0
  };
  var finalizedCBs_enqueue = handler;
  var finalizedCBs_on = function (x) {
    if (typeof x === "number") {
      return List.iter(handler, render_events.contents);
    }
    if (x.TAG === /* AddRenderMsg */0) {
      render_events.contents = List.append(render_events.contents, {
            hd: x._0,
            tl: /* [] */0
          });
      return ;
    }
    var msg = x._0;
    render_events.contents = List.filter(function (mg) {
            return msg !== mg;
          })(render_events.contents);
    
  };
  var finalizedCBs = {
    enqueue: finalizedCBs_enqueue,
    on: finalizedCBs_on
  };
  callbacks.contents = finalizedCBs;
  var pi_requestShutdown = function (param) {
    callbacks.contents = {
      enqueue: (function (_msg) {
          console.log("INVALID message enqueued when shut down");
          
        }),
      on: (function (param) {
          
        })
    };
    var cmd = Curry._1(shutdown, model.contents);
    Curry._1(pumperInterface.shutdown, cmd);
    
  };
  var render_string = function (param) {
    return Curry._1(pumperInterface.render_string, model.contents);
  };
  Curry._1(pumperInterface.startup, undefined);
  return {
          pushMsg: handler,
          shutdown: pi_requestShutdown,
          getHtmlString: render_string
        };
}

function programLoop(update, view, subscriptions, initModel, initCmd, x) {
  if (x === undefined) {
    return function (callbacks) {
      var oldSub = {
        contents: /* NoSub */0
      };
      var handleSubscriptionChange = function (model) {
        var newSub = Curry._1(subscriptions, model);
        oldSub.contents = Tea_sub.run(callbacks, callbacks, oldSub.contents, newSub);
        
      };
      return {
              startup: (function (param) {
                  Tea_cmd.run(callbacks, initCmd);
                  handleSubscriptionChange(initModel);
                  
                }),
              render_string: (function (model) {
                  return Vdom.renderToHtmlString(Curry._1(view, model));
                }),
              handleMsg: (function (model, msg) {
                  var match = Curry._2(update, model, msg);
                  var newModel = match[0];
                  Tea_cmd.run(callbacks, match[1]);
                  handleSubscriptionChange(newModel);
                  return newModel;
                }),
              shutdown: (function (cmd) {
                  Tea_cmd.run(callbacks, cmd);
                  oldSub.contents = Tea_sub.run(callbacks, callbacks, oldSub.contents, /* NoSub */0);
                  
                })
            };
    };
  }
  var parentNode = Caml_option.valFromOption(x);
  return function (callbacks) {
    var priorRenderedVdom = {
      contents: /* [] */0
    };
    var latestModel = {
      contents: initModel
    };
    var nextFrameID = {
      contents: undefined
    };
    var doRender = function (_delta) {
      var _id = nextFrameID.contents;
      if (_id === undefined) {
        return ;
      }
      var newVdom_0 = Curry._1(view, latestModel.contents);
      var newVdom = {
        hd: newVdom_0,
        tl: /* [] */0
      };
      var justRenderedVdom = Vdom.patchVNodesIntoElement(callbacks, parentNode, priorRenderedVdom.contents, newVdom);
      priorRenderedVdom.contents = justRenderedVdom;
      Curry._1(callbacks.contents.on, /* Render */0);
      nextFrameID.contents = undefined;
      
    };
    var scheduleRender = function (param) {
      var match = nextFrameID.contents;
      if (match !== undefined) {
        return ;
      }
      var id = window.requestAnimationFrame(doRender);
      nextFrameID.contents = id;
      
    };
    var clearPnode = function (param) {
      while(parentNode.childNodes.length > 0) {
        var firstChild = parentNode.firstChild;
        if (firstChild !== null) {
          parentNode.removeChild(firstChild);
        }
        
      };
      
    };
    var oldSub = {
      contents: /* NoSub */0
    };
    var handleSubscriptionChange = function (model) {
      var newSub = Curry._1(subscriptions, model);
      oldSub.contents = Tea_sub.run(callbacks, callbacks, oldSub.contents, newSub);
      
    };
    var handlerStartup = function (param) {
      clearPnode(undefined);
      Tea_cmd.run(callbacks, initCmd);
      handleSubscriptionChange(latestModel.contents);
      nextFrameID.contents = -1;
      doRender(16);
      
    };
    var render_string = function (model) {
      return Vdom.renderToHtmlString(Curry._1(view, model));
    };
    var handler = function (model, msg) {
      var match = Curry._2(update, model, msg);
      var newModel = match[0];
      latestModel.contents = newModel;
      Tea_cmd.run(callbacks, match[1]);
      scheduleRender(undefined);
      handleSubscriptionChange(newModel);
      return newModel;
    };
    var handlerShutdown = function (cmd) {
      nextFrameID.contents = undefined;
      Tea_cmd.run(callbacks, cmd);
      oldSub.contents = Tea_sub.run(callbacks, callbacks, oldSub.contents, /* NoSub */0);
      priorRenderedVdom.contents = /* [] */0;
      clearPnode(undefined);
      
    };
    return {
            startup: handlerStartup,
            render_string: render_string,
            handleMsg: handler,
            shutdown: handlerShutdown
          };
  };
}

function program(param, pnode, flags) {
  Web.polyfills(undefined);
  var match = Curry._1(param.init, flags);
  var initModel = match[0];
  var opnode = (pnode == null) ? undefined : Caml_option.some(pnode);
  var pumpInterface = programLoop(param.update, param.view, param.subscriptions, initModel, match[1], opnode);
  return programStateWrapper(initModel, pumpInterface, param.shutdown);
}

function standardProgram(param, pnode, args) {
  return program({
              init: param.init,
              update: param.update,
              view: param.view,
              subscriptions: param.subscriptions,
              shutdown: (function (_model) {
                  return /* NoCmd */0;
                })
            }, pnode, args);
}

function beginnerProgram(param, pnode, param$1) {
  var update = param.update;
  var model = param.model;
  return standardProgram({
              init: (function (param) {
                  return [
                          model,
                          /* NoCmd */0
                        ];
                }),
              update: (function (model, msg) {
                  return [
                          Curry._2(update, model, msg),
                          /* NoCmd */0
                        ];
                }),
              view: param.view,
              subscriptions: (function (_model) {
                  return /* NoSub */0;
                })
            }, pnode, undefined);
}

var map = Vdom.map;

exports.programStateWrapper = programStateWrapper;
exports.programLoop = programLoop;
exports.program = program;
exports.standardProgram = standardProgram;
exports.beginnerProgram = beginnerProgram;
exports.map = map;
/* No side effect */
