// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Web_node = require("./web_node.js");
var Web_window = require("./web_window.js");

function polyfills(param) {
  Web_node.remove_polyfill(undefined);
  Web_window.requestAnimationFrame_polyfill(undefined);
  
}

var $$Event;

var $$Node;

var $$Document;

var $$Date;

var $$Window;

var $$Location;

var Json;

var $$XMLHttpRequest;

var $$FormData;

exports.$$Event = $$Event;
exports.$$Node = $$Node;
exports.$$Document = $$Document;
exports.$$Date = $$Date;
exports.$$Window = $$Window;
exports.$$Location = $$Location;
exports.Json = Json;
exports.$$XMLHttpRequest = $$XMLHttpRequest;
exports.$$FormData = $$FormData;
exports.polyfills = polyfills;
/* No side effect */
