// Generated by BUCKLESCRIPT VERSION 1.5.2, PLEASE EDIT WITH CARE
'use strict';


function setItem($$window, key, value) {
  var match = $$window.localStorage;
  if (match !== undefined) {
    return match.setItem(key, value);
  }
  else {
    return /* () */0;
  }
}

function getItem($$window, key) {
  var match = $$window.localStorage;
  if (match !== undefined) {
    var res = match.getItem(key);
    if (res === "") {
      return /* None */0;
    }
    else {
      return /* Some */[res];
    }
  }
  else {
    return /* None */0;
  }
}

exports.setItem = setItem;
exports.getItem = getItem;
/* No side effect */
