// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';


var Result = 0;

var Cmd = 0;

var Sub = 0;

var App = 0;

var Debug = 0;

var Html = 0;

var Html2 = 0;

var Svg = 0;

var Program = 0;

var Time = 0;

var Json = 0;

var Navigation = 0;

var Random = 0;

var AnimationFrame = 0;

var Mouse = 0;

var Http = 0;

var Ex = 0;

exports.Result = Result;
exports.Cmd = Cmd;
exports.Sub = Sub;
exports.App = App;
exports.Debug = Debug;
exports.Html = Html;
exports.Html2 = Html2;
exports.Svg = Svg;
exports.Program = Program;
exports.Time = Time;
exports.Json = Json;
exports.Navigation = Navigation;
exports.Random = Random;
exports.AnimationFrame = AnimationFrame;
exports.Mouse = Mouse;
exports.Http = Http;
exports.Ex = Ex;
/* No side effect */
