// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");

function spawn(initState, update, shutdown) {
  var state = /* record */[/* contents */Js_primitive.some(initState)];
  return (function (procMsg) {
      var match = state[0];
      if (match !== undefined) {
        var model = Js_primitive.valFromOption(match);
        if (procMsg) {
          state[0] = Curry._2(update, model, procMsg[0]);
          return /* () */0;
        } else {
          Curry._1(shutdown, model);
          state[0] = undefined;
          return /* () */0;
        }
      } else {
        return /* () */0;
      }
    });
}

var testing1 = 42;

exports.spawn = spawn;
exports.testing1 = testing1;
/* No side effect */
