// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Vdom = require("./vdom.js");
var Block = require("bs-platform/lib/js/block.js");
var Bytes = require("bs-platform/lib/js/bytes.js");
var Curry = require("bs-platform/lib/js/curry.js");
var $$String = require("bs-platform/lib/js/string.js");
var Tea_html = require("./tea_html.js");
var Caml_string = require("bs-platform/lib/js/caml_string.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");

function text(str) {
  return /* Text */Block.__(1, [str]);
}

function node($staropt$star, tagName, $staropt$star$1, $staropt$star$2, props, nodes) {
  var namespace = $staropt$star !== undefined ? $staropt$star : "";
  var key = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  var unique = $staropt$star$2 !== undefined ? $staropt$star$2 : "";
  return Vdom.fullnode(namespace, tagName, key, unique, props, nodes);
}

var lazy1 = Vdom.lazyGen;

function h1($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "h1", key, unique, props, nodes);
}

function h2($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "h2", key, unique, props, nodes);
}

function h3($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "h3", key, unique, props, nodes);
}

function h4($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "h4", key, unique, props, nodes);
}

function h5($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "h5", key, unique, props, nodes);
}

function h6($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "h6", key, unique, props, nodes);
}

function div($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "div", key, unique, props, nodes);
}

function p($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "p", key, unique, props, nodes);
}

function hr($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "hr", key, unique, props, nodes);
}

function pre($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "pre", key, unique, props, nodes);
}

function blockquote($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "blockquote", key, unique, props, nodes);
}

function span($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "span", key, unique, props, nodes);
}

function a($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "a", key, unique, props, nodes);
}

function code($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "code", key, unique, props, nodes);
}

function em($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "em", key, unique, props, nodes);
}

function strong($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "strong", key, unique, props, nodes);
}

function i($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "i", key, unique, props, nodes);
}

function b($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "b", key, unique, props, nodes);
}

function u($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "u", key, unique, props, nodes);
}

function sub($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "sub", key, unique, props, nodes);
}

function sup($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "sup", key, unique, props, nodes);
}

function br(props) {
  return Vdom.fullnode("", "br", "br", "br", props, /* [] */0);
}

function br$prime($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "br", key, unique, props, nodes);
}

function ol($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "ol", key, unique, props, nodes);
}

function ul($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "ul", key, unique, props, nodes);
}

function li($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "li", key, unique, props, nodes);
}

function dl($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "dl", key, unique, props, nodes);
}

function dt($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "dt", key, unique, props, nodes);
}

function dd($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "dd", key, unique, props, nodes);
}

function img($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "img", key, unique, props, nodes);
}

function iframe($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "iframe", key, unique, props, nodes);
}

function canvas($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "canvas", key, unique, props, nodes);
}

function math($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "math", key, unique, props, nodes);
}

function form($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "form", key, unique, props, nodes);
}

function input$prime($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "input", key, unique, props, nodes);
}

function textarea($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "textarea", key, unique, props, nodes);
}

function button($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "button", key, unique, props, nodes);
}

function select($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "select", key, unique, props, nodes);
}

function option$prime($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "option", key, unique, props, nodes);
}

function optgroup($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "optgroup", key, unique, props, nodes);
}

function label($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "label", key, unique, props, nodes);
}

function fieldset($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "fieldset", key, unique, props, nodes);
}

function legend($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "legend", key, unique, props, nodes);
}

function section($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "section", key, unique, props, nodes);
}

function nav($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "nav", key, unique, props, nodes);
}

function article($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "article", key, unique, props, nodes);
}

function aside($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "aside", key, unique, props, nodes);
}

function header($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "header", key, unique, props, nodes);
}

function footer($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "footer", key, unique, props, nodes);
}

function address($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "address", key, unique, props, nodes);
}

function main($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "main", key, unique, props, nodes);
}

function body($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "body", key, unique, props, nodes);
}

function figure($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "figure", key, unique, props, nodes);
}

function figcaption($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "figcaption", key, unique, props, nodes);
}

function table($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "table", key, unique, props, nodes);
}

function caption($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "caption", key, unique, props, nodes);
}

function colgroup($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "colgroup", key, unique, props, nodes);
}

function col($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "col", key, unique, props, nodes);
}

function tbody($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "tbody", key, unique, props, nodes);
}

function thead($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "thead", key, unique, props, nodes);
}

function tfoot($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "tfoot", key, unique, props, nodes);
}

function tr($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "tr", key, unique, props, nodes);
}

function th($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "th", key, unique, props, nodes);
}

function td($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "td", key, unique, props, nodes);
}

function datalist($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "datalist", key, unique, props, nodes);
}

function keygen($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "keygen", key, unique, props, nodes);
}

function output($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "output", key, unique, props, nodes);
}

function progress($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "progress", key, unique, props, nodes);
}

function meter($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "meter", key, unique, props, nodes);
}

function audio($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "audio", key, unique, props, nodes);
}

function video($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "video", key, unique, props, nodes);
}

function source($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "source", key, unique, props, nodes);
}

function track($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "track", key, unique, props, nodes);
}

function embed($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "embed", key, unique, props, nodes);
}

function object$prime($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "object", key, unique, props, nodes);
}

function param($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "param", key, unique, props, nodes);
}

function ins($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "ins", key, unique, props, nodes);
}

function del($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "del", key, unique, props, nodes);
}

function small($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "small", key, unique, props, nodes);
}

function cite($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "cite", key, unique, props, nodes);
}

function dfn($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "dfn", key, unique, props, nodes);
}

function abbr($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "abbr", key, unique, props, nodes);
}

function time($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "time", key, unique, props, nodes);
}

function var$prime($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "var", key, unique, props, nodes);
}

function samp($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "samp", key, unique, props, nodes);
}

function kbd($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "kbd", key, unique, props, nodes);
}

function s($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "s", key, unique, props, nodes);
}

function q($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "q", key, unique, props, nodes);
}

function mark($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "mark", key, unique, props, nodes);
}

function ruby($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "ruby", key, unique, props, nodes);
}

function rt($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "rt", key, unique, props, nodes);
}

function rp($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "rp", key, unique, props, nodes);
}

function bdi($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "bdi", key, unique, props, nodes);
}

function bdo($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "bdo", key, unique, props, nodes);
}

function wbr($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "wbr", key, unique, props, nodes);
}

function details($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "details", key, unique, props, nodes);
}

function summary($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "summary", key, unique, props, nodes);
}

function menuitem($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "menuitem", key, unique, props, nodes);
}

function menu($staropt$star, $staropt$star$1, props, nodes) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "menu", key, unique, props, nodes);
}

function meta($staropt$star, $staropt$star$1, props) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "meta", key, unique, props, /* [] */0);
}

function style($staropt$star, $staropt$star$1, props, content) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "style", key, unique, props, /* :: */[
              /* Text */Block.__(1, [content]),
              /* [] */0
            ]);
}

function title($staropt$star, $staropt$star$1, props, content) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "title", key, unique, props, /* :: */[
              /* Text */Block.__(1, [content]),
              /* [] */0
            ]);
}

function link($staropt$star, $staropt$star$1, props) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  var unique = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return Vdom.fullnode("", "link", key, unique, props, /* [] */0);
}

function style$1(key, value) {
  return style(undefined, undefined, key, value);
}

function styles(s) {
  return /* Style */Block.__(4, [s]);
}

function class$prime(name) {
  return /* RawProp */Block.__(0, [
            "className",
            name
          ]);
}

function classList(classes) {
  var name = $$String.concat(" ", List.map((function (param) {
              return param[0];
            }), List.filter((function (param) {
                    return param[1];
                  }))(classes)));
  return /* RawProp */Block.__(0, [
            "className",
            name
          ]);
}

function id(str) {
  return /* RawProp */Block.__(0, [
            "id",
            str
          ]);
}

function title$1(str) {
  return /* Attribute */Block.__(1, [
            "",
            "title",
            str
          ]);
}

function hidden(b) {
  if (b) {
    return /* RawProp */Block.__(0, [
              "hidden",
              "hidden"
            ]);
  } else {
    return /* NoProp */0;
  }
}

function type$prime(typ) {
  return /* RawProp */Block.__(0, [
            "type",
            typ
          ]);
}

function value(str) {
  return /* RawProp */Block.__(0, [
            "value",
            str
          ]);
}

function defaultValue(str) {
  return /* RawProp */Block.__(0, [
            "defaultValue",
            str
          ]);
}

function checked(b) {
  if (b) {
    return /* RawProp */Block.__(0, [
              "checked",
              "checked"
            ]);
  } else {
    return /* NoProp */0;
  }
}

function placeholder(str) {
  return /* RawProp */Block.__(0, [
            "placeholder",
            str
          ]);
}

function selected(b) {
  if (b) {
    return /* Attribute */Block.__(1, [
              "",
              "selected",
              "true"
            ]);
  } else {
    return /* NoProp */0;
  }
}

function accept(c) {
  return /* Attribute */Block.__(1, [
            "",
            "accept",
            c
          ]);
}

function acceptCharset(c) {
  return /* Attribute */Block.__(1, [
            "",
            "accept-charset",
            c
          ]);
}

function action(a) {
  return /* RawProp */Block.__(0, [
            "action",
            a
          ]);
}

function autocomplete(b) {
  return /* RawProp */Block.__(0, [
            "autocomplete",
            b ? "on" : "off"
          ]);
}

function autofocus(b) {
  if (b) {
    return /* RawProp */Block.__(0, [
              "autofocus",
              "autofocus"
            ]);
  } else {
    return /* NoProp */0;
  }
}

function disabled(b) {
  if (b) {
    return /* Attribute */Block.__(1, [
              "",
              "disabled",
              "true"
            ]);
  } else {
    return /* NoProp */0;
  }
}

function enctype(encoding) {
  return /* Attribute */Block.__(1, [
            "",
            "enctype",
            encoding
          ]);
}

function formaction(url) {
  return /* Attribute */Block.__(1, [
            "",
            "formaction",
            url
          ]);
}

function list(value) {
  return /* Attribute */Block.__(1, [
            "",
            "list",
            value
          ]);
}

function minlength(n) {
  return /* Attribute */Block.__(1, [
            "",
            "minlength",
            String(n)
          ]);
}

function maxlength(n) {
  return /* Attribute */Block.__(1, [
            "",
            "maxlength",
            String(n)
          ]);
}

function method$prime(m) {
  return /* RawProp */Block.__(0, [
            "method",
            m
          ]);
}

function multiple(b) {
  if (b) {
    return /* RawProp */Block.__(0, [
              "multiple",
              "multiple"
            ]);
  } else {
    return /* NoProp */0;
  }
}

function name(str) {
  return /* RawProp */Block.__(0, [
            "name",
            str
          ]);
}

function novalidate(b) {
  if (b) {
    return /* RawProp */Block.__(0, [
              "novalidate",
              "novalidate"
            ]);
  } else {
    return /* NoProp */0;
  }
}

function pattern(p) {
  return /* RawProp */Block.__(0, [
            "pattern",
            p
          ]);
}

function readonly(b) {
  if (b) {
    return /* RawProp */Block.__(0, [
              "readonly",
              "readonly"
            ]);
  } else {
    return /* NoProp */0;
  }
}

function required(b) {
  if (b) {
    return /* RawProp */Block.__(0, [
              "required",
              "required"
            ]);
  } else {
    return /* NoProp */0;
  }
}

function size(n) {
  return /* Attribute */Block.__(1, [
            "",
            "size",
            String(n)
          ]);
}

function for$prime(str) {
  return /* RawProp */Block.__(0, [
            "htmlFor",
            str
          ]);
}

function form$1(value) {
  return /* Attribute */Block.__(1, [
            "",
            "form",
            value
          ]);
}

function max(value) {
  return /* Attribute */Block.__(1, [
            "",
            "max",
            value
          ]);
}

function min(value) {
  return /* Attribute */Block.__(1, [
            "",
            "min",
            value
          ]);
}

function step(value) {
  return /* Attribute */Block.__(1, [
            "",
            "step",
            value
          ]);
}

function cols(n) {
  return /* Attribute */Block.__(1, [
            "",
            "cols",
            String(n)
          ]);
}

function rows(n) {
  return /* Attribute */Block.__(1, [
            "",
            "rows",
            String(n)
          ]);
}

function wrap(value) {
  return /* RawProp */Block.__(0, [
            "wrap",
            value
          ]);
}

function href(str) {
  return /* Attribute */Block.__(1, [
            "",
            "href",
            str
          ]);
}

function target(t) {
  return /* RawProp */Block.__(0, [
            "target",
            t
          ]);
}

function download(b) {
  if (b) {
    return /* RawProp */Block.__(0, [
              "download",
              ""
            ]);
  } else {
    return /* NoProp */0;
  }
}

function downloadAs(name) {
  return /* RawProp */Block.__(0, [
            "download",
            name
          ]);
}

function hreflang(code) {
  return /* RawProp */Block.__(0, [
            "hreflang",
            code
          ]);
}

function media(value) {
  return /* Attribute */Block.__(1, [
            "",
            "media",
            value
          ]);
}

function ping(url) {
  return /* RawProp */Block.__(0, [
            "ping",
            url
          ]);
}

function rel(value) {
  return /* Attribute */Block.__(1, [
            "",
            "rel",
            value
          ]);
}

function ismap(b) {
  if (b) {
    return /* RawProp */Block.__(0, [
              "ismap",
              "ismap"
            ]);
  } else {
    return /* NoProp */0;
  }
}

function usemap(name) {
  return /* RawProp */Block.__(0, [
            "usemap",
            name
          ]);
}

function shape(value) {
  return /* RawProp */Block.__(0, [
            "shape",
            value
          ]);
}

function coords(value) {
  return /* RawProp */Block.__(0, [
            "coords",
            value
          ]);
}

function src(str) {
  return /* Attribute */Block.__(1, [
            "",
            "src",
            str
          ]);
}

function height(n) {
  return /* Attribute */Block.__(1, [
            "",
            "height",
            String(n)
          ]);
}

function width(n) {
  return /* Attribute */Block.__(1, [
            "",
            "width",
            String(n)
          ]);
}

function alt(value) {
  return /* RawProp */Block.__(0, [
            "alt",
            value
          ]);
}

function autoplay(b) {
  if (b) {
    return /* RawProp */Block.__(0, [
              "autoplay",
              "autoplay"
            ]);
  } else {
    return /* NoProp */0;
  }
}

function controls(b) {
  if (b) {
    return /* RawProp */Block.__(0, [
              "controls",
              "controls"
            ]);
  } else {
    return /* NoProp */0;
  }
}

function loop(b) {
  if (b) {
    return /* RawProp */Block.__(0, [
              "loop",
              "loop"
            ]);
  } else {
    return /* NoProp */0;
  }
}

function preload(value) {
  return /* RawProp */Block.__(0, [
            "preload",
            value
          ]);
}

function poster(url) {
  return /* RawProp */Block.__(0, [
            "poster",
            url
          ]);
}

function $$default(b) {
  if (b) {
    return /* RawProp */Block.__(0, [
              "default",
              "default"
            ]);
  } else {
    return /* NoProp */0;
  }
}

function kind(value) {
  return /* RawProp */Block.__(0, [
            "kind",
            value
          ]);
}

function srclang(code) {
  return /* RawProp */Block.__(0, [
            "srclang",
            code
          ]);
}

function sandbox(value) {
  return /* RawProp */Block.__(0, [
            "sandbox",
            value
          ]);
}

function seamless(b) {
  if (b) {
    return /* RawProp */Block.__(0, [
              "seamless",
              "seamless"
            ]);
  } else {
    return /* NoProp */0;
  }
}

function srcdoc(value) {
  return /* RawProp */Block.__(0, [
            "srcdoc",
            value
          ]);
}

function reversed(b) {
  if (b) {
    return /* RawProp */Block.__(0, [
              "reversed",
              "reversed"
            ]);
  } else {
    return /* NoProp */0;
  }
}

function start(n) {
  return /* RawProp */Block.__(0, [
            "start",
            String(n)
          ]);
}

function colspan(n) {
  return /* Attribute */Block.__(1, [
            "",
            "colspan",
            String(n)
          ]);
}

function rowspan(n) {
  return /* Attribute */Block.__(1, [
            "",
            "rowspan",
            String(n)
          ]);
}

function headers(value) {
  return /* RawProp */Block.__(0, [
            "headers",
            value
          ]);
}

function scope(value) {
  return /* RawProp */Block.__(0, [
            "scope",
            value
          ]);
}

function align(value) {
  return /* RawProp */Block.__(0, [
            "align",
            value
          ]);
}

function async(b) {
  if (b) {
    return /* RawProp */Block.__(0, [
              "async",
              "async"
            ]);
  } else {
    return /* NoProp */0;
  }
}

function charset(value) {
  return /* Attribute */Block.__(1, [
            "",
            "charset",
            value
          ]);
}

function content(value) {
  return /* Attribute */Block.__(1, [
            "",
            "content",
            value
          ]);
}

function defer(b) {
  if (b) {
    return /* RawProp */Block.__(0, [
              "defer",
              "defer"
            ]);
  } else {
    return /* NoProp */0;
  }
}

function httpEquiv(value) {
  return /* RawProp */Block.__(0, [
            "http-equiv",
            value
          ]);
}

function language(value) {
  return /* RawProp */Block.__(0, [
            "language",
            value
          ]);
}

function scoped(value) {
  return /* RawProp */Block.__(0, [
            "scoped",
            value
          ]);
}

function accesskey(ch) {
  return /* RawProp */Block.__(0, [
            "accesskey",
            Caml_string.bytes_to_string(Bytes.make(1, ch))
          ]);
}

function contenteditable(b) {
  if (b) {
    return /* RawProp */Block.__(0, [
              "contenteditable",
              "contenteditable"
            ]);
  } else {
    return /* NoProp */0;
  }
}

function contextmenu(id) {
  return /* Attribute */Block.__(1, [
            "",
            "contextmenu",
            id
          ]);
}

function dir(value) {
  return /* RawProp */Block.__(0, [
            "dir",
            value
          ]);
}

function draggable(value) {
  return /* Attribute */Block.__(1, [
            "",
            "draggable",
            value
          ]);
}

function dropzone(value) {
  return /* RawProp */Block.__(0, [
            "dropzone",
            value
          ]);
}

function itemprop(value) {
  return /* Attribute */Block.__(1, [
            "",
            "itemprop",
            value
          ]);
}

function lang(code) {
  return /* RawProp */Block.__(0, [
            "lang",
            code
          ]);
}

function spellcheck(b) {
  if (b) {
    return /* RawProp */Block.__(0, [
              "spellcheck",
              "spellcheck"
            ]);
  } else {
    return /* NoProp */0;
  }
}

function tabindex(n) {
  return /* Attribute */Block.__(1, [
            "",
            "tabindex",
            String(n)
          ]);
}

function challenge(value) {
  return /* Attribute */Block.__(1, [
            "",
            "challenge",
            value
          ]);
}

function keytype(value) {
  return /* RawProp */Block.__(0, [
            "keytype",
            value
          ]);
}

function cite$1(url) {
  return /* RawProp */Block.__(0, [
            "cite",
            url
          ]);
}

function datetime(value) {
  return /* Attribute */Block.__(1, [
            "",
            "datetime",
            value
          ]);
}

function pubdate(value) {
  return /* Attribute */Block.__(1, [
            "",
            "pubdate",
            value
          ]);
}

function manifest(value) {
  return /* Attribute */Block.__(1, [
            "",
            "manifest",
            value
          ]);
}

var Attributes = /* module */[
  /* noProp : NoProp */0,
  /* style */style$1,
  /* styles */styles,
  /* class' */class$prime,
  /* classList */classList,
  /* id */id,
  /* title */title$1,
  /* hidden */hidden,
  /* type' */type$prime,
  /* value */value,
  /* defaultValue */defaultValue,
  /* checked */checked,
  /* placeholder */placeholder,
  /* selected */selected,
  /* accept */accept,
  /* acceptCharset */acceptCharset,
  /* action */action,
  /* autocomplete */autocomplete,
  /* autofocus */autofocus,
  /* disabled */disabled,
  /* enctype */enctype,
  /* formaction */formaction,
  /* list */list,
  /* minlength */minlength,
  /* maxlength */maxlength,
  /* method' */method$prime,
  /* multiple */multiple,
  /* name */name,
  /* novalidate */novalidate,
  /* pattern */pattern,
  /* readonly */readonly,
  /* required */required,
  /* size */size,
  /* for' */for$prime,
  /* form */form$1,
  /* max */max,
  /* min */min,
  /* step */step,
  /* cols */cols,
  /* rows */rows,
  /* wrap */wrap,
  /* href */href,
  /* target */target,
  /* download */download,
  /* downloadAs */downloadAs,
  /* hreflang */hreflang,
  /* media */media,
  /* ping */ping,
  /* rel */rel,
  /* ismap */ismap,
  /* usemap */usemap,
  /* shape */shape,
  /* coords */coords,
  /* src */src,
  /* height */height,
  /* width */width,
  /* alt */alt,
  /* autoplay */autoplay,
  /* controls */controls,
  /* loop */loop,
  /* preload */preload,
  /* poster */poster,
  /* default */$$default,
  /* kind */kind,
  /* srclang */srclang,
  /* sandbox */sandbox,
  /* seamless */seamless,
  /* srcdoc */srcdoc,
  /* reversed */reversed,
  /* start */start,
  /* colspan */colspan,
  /* rowspan */rowspan,
  /* headers */headers,
  /* scope */scope,
  /* align */align,
  /* async */async,
  /* charset */charset,
  /* content */content,
  /* defer */defer,
  /* httpEquiv */httpEquiv,
  /* language */language,
  /* scoped */scoped,
  /* accesskey */accesskey,
  /* contenteditable */contenteditable,
  /* contextmenu */contextmenu,
  /* dir */dir,
  /* draggable */draggable,
  /* dropzone */dropzone,
  /* itemprop */itemprop,
  /* lang */lang,
  /* spellcheck */spellcheck,
  /* tabindex */tabindex,
  /* challenge */challenge,
  /* keytype */keytype,
  /* cite */cite$1,
  /* datetime */datetime,
  /* pubdate */pubdate,
  /* manifest */manifest
];

var onCB = Vdom.onCB;

var onMsg = Vdom.onMsg;

function onClick(msg) {
  return Vdom.onMsg("click", msg);
}

function onDoubleClick(msg) {
  return Vdom.onMsg("dblclick", msg);
}

function onMouseDown(msg) {
  return Vdom.onMsg("mousedown", msg);
}

function onMouseUp(msg) {
  return Vdom.onMsg("mouseup", msg);
}

function onMouseEnter(msg) {
  return Vdom.onMsg("mouseenter", msg);
}

function onMouseLeave(msg) {
  return Vdom.onMsg("mouseleave", msg);
}

function onMouseOver(msg) {
  return Vdom.onMsg("mouseover", msg);
}

function onMouseOut(msg) {
  return Vdom.onMsg("mouseout", msg);
}

function onInputOpt($staropt$star, msg) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  return Vdom.onCB("input", key, (function (ev) {
                var match = ev.target;
                if (match !== undefined) {
                  var match$1 = match.value;
                  if (match$1 !== undefined) {
                    return Curry._1(msg, match$1);
                  } else {
                    return undefined;
                  }
                }
                
              }));
}

function onInput($staropt$star, msg) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  return onInputOpt(key, (function (ev) {
                return Js_primitive.some(Curry._1(msg, ev));
              }));
}

function onCheckOpt($staropt$star, msg) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  return Vdom.onCB("change", key, (function (ev) {
                var match = ev.target;
                if (match !== undefined) {
                  var match$1 = match.checked;
                  if (match$1 !== undefined) {
                    return Curry._1(msg, match$1);
                  } else {
                    return undefined;
                  }
                }
                
              }));
}

function onCheck($staropt$star, msg) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  return onCheckOpt(key, (function (ev) {
                return Js_primitive.some(Curry._1(msg, ev));
              }));
}

function onChangeOpt($staropt$star, msg) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  return Vdom.onCB("change", key, (function (ev) {
                var match = ev.target;
                if (match !== undefined) {
                  var match$1 = match.value;
                  if (match$1 !== undefined) {
                    return Curry._1(msg, match$1);
                  } else {
                    return undefined;
                  }
                }
                
              }));
}

function onChange($staropt$star, msg) {
  var key = $staropt$star !== undefined ? $staropt$star : "";
  return onChangeOpt(key, (function (ev) {
                return Js_primitive.some(Curry._1(msg, ev));
              }));
}

function onBlur(msg) {
  return Vdom.onMsg("blur", msg);
}

function onFocus(msg) {
  return Vdom.onMsg("focus", msg);
}

var Events = /* module */[
  /* onCB */onCB,
  /* onMsg */onMsg,
  /* on */Tea_html.on,
  /* onWithOptions */Tea_html.onWithOptions,
  /* defaultOptions */Tea_html.defaultOptions,
  /* targetValue */Tea_html.targetValue,
  /* targetChecked */Tea_html.targetChecked,
  /* keyCode */Tea_html.keyCode,
  /* onClick */onClick,
  /* onDoubleClick */onDoubleClick,
  /* onMouseDown */onMouseDown,
  /* onMouseUp */onMouseUp,
  /* onMouseEnter */onMouseEnter,
  /* onMouseLeave */onMouseLeave,
  /* onMouseOver */onMouseOver,
  /* onMouseOut */onMouseOut,
  /* onInputOpt */onInputOpt,
  /* onInput */onInput,
  /* onCheckOpt */onCheckOpt,
  /* onCheck */onCheck,
  /* onChangeOpt */onChangeOpt,
  /* onChange */onChange,
  /* onBlur */onBlur,
  /* onFocus */onFocus
];

var Cmds = 0;

var noNode = Vdom.noNode;

exports.Cmds = Cmds;
exports.text = text;
exports.node = node;
exports.noNode = noNode;
exports.lazy1 = lazy1;
exports.h1 = h1;
exports.h2 = h2;
exports.h3 = h3;
exports.h4 = h4;
exports.h5 = h5;
exports.h6 = h6;
exports.div = div;
exports.p = p;
exports.hr = hr;
exports.pre = pre;
exports.blockquote = blockquote;
exports.span = span;
exports.a = a;
exports.code = code;
exports.em = em;
exports.strong = strong;
exports.i = i;
exports.b = b;
exports.u = u;
exports.sub = sub;
exports.sup = sup;
exports.br = br;
exports.br$prime = br$prime;
exports.ol = ol;
exports.ul = ul;
exports.li = li;
exports.dl = dl;
exports.dt = dt;
exports.dd = dd;
exports.img = img;
exports.iframe = iframe;
exports.canvas = canvas;
exports.math = math;
exports.form = form;
exports.input$prime = input$prime;
exports.textarea = textarea;
exports.button = button;
exports.select = select;
exports.option$prime = option$prime;
exports.optgroup = optgroup;
exports.label = label;
exports.fieldset = fieldset;
exports.legend = legend;
exports.section = section;
exports.nav = nav;
exports.article = article;
exports.aside = aside;
exports.header = header;
exports.footer = footer;
exports.address = address;
exports.main = main;
exports.body = body;
exports.figure = figure;
exports.figcaption = figcaption;
exports.table = table;
exports.caption = caption;
exports.colgroup = colgroup;
exports.col = col;
exports.tbody = tbody;
exports.thead = thead;
exports.tfoot = tfoot;
exports.tr = tr;
exports.th = th;
exports.td = td;
exports.datalist = datalist;
exports.keygen = keygen;
exports.output = output;
exports.progress = progress;
exports.meter = meter;
exports.audio = audio;
exports.video = video;
exports.source = source;
exports.track = track;
exports.embed = embed;
exports.object$prime = object$prime;
exports.param = param;
exports.ins = ins;
exports.del = del;
exports.small = small;
exports.cite = cite;
exports.dfn = dfn;
exports.abbr = abbr;
exports.time = time;
exports.var$prime = var$prime;
exports.samp = samp;
exports.kbd = kbd;
exports.s = s;
exports.q = q;
exports.mark = mark;
exports.ruby = ruby;
exports.rt = rt;
exports.rp = rp;
exports.bdi = bdi;
exports.bdo = bdo;
exports.wbr = wbr;
exports.details = details;
exports.summary = summary;
exports.menuitem = menuitem;
exports.menu = menu;
exports.meta = meta;
exports.style = style;
exports.title = title;
exports.link = link;
exports.Attributes = Attributes;
exports.Events = Events;
/* Tea_html Not a pure module */
