// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Web_node = require("./web_node.js");
var Web_window = require("./web_window.js");

function polyfills(param) {
  Web_node.remove_polyfill(/* () */0);
  Web_window.requestAnimationFrame_polyfill(/* () */0);
  return /* () */0;
}

var Event = 0;

var Node = 0;

var Document = 0;

var $$Date = 0;

var Window = 0;

var Location = 0;

var Json = 0;

var $$XMLHttpRequest = 0;

var FormData = 0;

exports.Event = Event;
exports.Node = Node;
exports.Document = Document;
exports.$$Date = $$Date;
exports.Window = Window;
exports.Location = Location;
exports.Json = Json;
exports.$$XMLHttpRequest = $$XMLHttpRequest;
exports.FormData = FormData;
exports.polyfills = polyfills;
/* No side effect */
