// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Js_json = require("bs-platform/lib/js/js_json.js");

function string_of_json($staropt$star, value) {
  var indent = $staropt$star !== undefined ? $staropt$star : 2;
  if (value !== undefined) {
    try {
      return JSON.stringify(value, null, indent);
    }
    catch (exn){
      return "";
    }
  } else {
    return "undefined";
  }
}

function of_type(_v, x) {
  return x;
}

var classify = Js_json.classify;

var test = Js_json.test;

var decodeString = Js_json.decodeString;

var decodeNumber = Js_json.decodeNumber;

var decodeObject = Js_json.decodeObject;

var decodeArray = Js_json.decodeArray;

var decodeBoolean = Js_json.decodeBoolean;

var decodeNull = Js_json.decodeNull;

var $$null = null;

exports.classify = classify;
exports.test = test;
exports.decodeString = decodeString;
exports.decodeNumber = decodeNumber;
exports.decodeObject = decodeObject;
exports.decodeArray = decodeArray;
exports.decodeBoolean = decodeBoolean;
exports.decodeNull = decodeNull;
exports.string_of_json = string_of_json;
exports.of_type = of_type;
exports.$$null = $$null;
/* No side effect */
